stages:
  - build
  - uploadConfiguration
  - qualif
  - preprod
  - production

variables:

#build:
#  stage: build
#  before_script: []
#  script:
#    - echo build
#  after_script: []


uploadConfiguration:
  stage: uploadConfiguration
  only:
  - master
  script:
    - chmod +x ./sweagle_scripts/*.sh
    - echo send configuration to Sweagle
    - ./sweagle_scripts/uploadFileToSweagle.sh
    - echo configuration sent
  when: on_sucess
  # possible values always, on_success, on_failure, manual

deployTest:
  stage: qualif
  only:
  - master
  variables:
    MDS: MyAPP_TEST_V1
    VALIDATOR: myValidator
    APPLI: MyAPP
    ENVRT: TEST
  before_script:
    - echo check configuration from Sweagle
    - chmod +x ./sweagle_scripts/*.sh
    - ./sweagle_scripts/SweagleCheckConfigByMDS.sh $MDS
    - ./sweagle_scripts/SweagleCheckConfigByMdsValidator.sh $MDS $VALIDATOR
    # SweagleGetConfigByAppEnv is a wrapper of getConfigByMdsParserArgs.sh
    # customized to match an App and Env to an MDS
    - ./sweagle_scripts/SweagleGetConfigByAppEnv.sh $APPLI $ENVRT
  script:
    - echo deploy TEST environment
    - echo run tests
  when: on_success
  # possible values always, on_success, on_failure, manual

#staging:
#  stage: staging
#  only:
#    - release
#  before_script: [Use Sweagle again]
#  script:
#    - echo deploy to staging


#production:
#  stage: production
#  before_script: [Use Sweagle again]
#  script:
#    - echo deploy to production
#  when: manual
