stages:
  - build
  - uploadConfiguration
  - test
  - staging
  - production

variables:
  CONFIG_DIR: "<DIRECTORY OR FILE WHERE YOU PUT YOUR CONFIG TO UPLOAD TO SWEAGLE>"
  SWEAGLE_SCRIPTS_DIR: "<DIRECTORY WHERE YOU PUT YOUR SWEAGLE SCRIPTS, EACH NODE SEPARATED BY COMMA>"
  SWEAGLE_PATH: "<PATH IN DATA MODEL WHERE YOU WANT TO PUT YOUR CONFIG DATA>"
  SWEAGLE_MDS: "<METADATASET YOU WANT TO GET CONFIG DATA FROM>"
  SWEAGLE_VALIDATORS: "<OPTIONAL, LIST OF CUSTOM VALIDATORS, SEPARATED BY SPACES, USED TO CHECK YOUR CONFIG>"
  SWEAGLE_EXPORTER: "<EXPORTER USED TO RETRIEVE YOUR CONFIG>"
  SWEAGLE_EXPORTER_ARGS: "<OPTIONAL, EXPORTER ARGUMENTS IF ANY, SEPARATED BY COMMA>"
  SWEAGLE_EXPORTER_FORMAT: "<OPTIONAL, FORMAT USED FOR DOWNLOADED CONFIG, PROPS (DEFAULT), YAML, JSON, XML>"
  SWEAGLE_EXPORTER_OUTPUT: "<OPTIONAL, TARGET FILE TO EXPORT CONFIG DATA TO, DEFAULT OUTPUT IS SCREEN>"

#build:
#  stage: build
#  before_script: []
#  script:
#    - echo build
#  after_script: []


uploadConfiguration:
  stage: uploadConfiguration
  only:
  - master
  script:
    - echo **********
    - echo *** Send configuration to Sweagle
    - chmod +x $SWEAGLE_SCRIPTS_DIR/*.sh
    - $SWEAGLE_SCRIPTS_DIR/uploadDirToSweagle.sh $SWEAGLE_PATH $CONFIG_DIR
    - echo *** Configuration sent
  when: on_success
  # possible values always, on_success, on_failure, manual

deployTestEnvironment:
  stage: test
  only:
  - master
  variables:
    # specific variables for this step
  before_script:
    - echo **********
    - echo *** Check configuration from Sweagle
    - chmod +x $SWEAGLE_SCRIPTS_DIR/*.sh
    - $SWEAGLE_SCRIPTS_DIR/checkAllConfigByMdsValidator.sh $SWEAGLE_MDS $SWEAGLE_VALIDATORS'
    # you may create your own wrapper of Sweagle scripts to match an App or Env to an MDS
    echo *** Retrieve lastest valid configuration from Sweagle
    echo *** Sweagle will also fill token values, if any
    # Store your config snapshot in order to be able to retrieve it
    - $SWEAGLE_SCRIPTS_DIR/storeConfigSnapshotByMds.sh $SWEAGLE_MDS
    # Download your config using exporter
    - $SWEAGLE_SCRIPTS_DIR/getConfigByMdsParserArgs.sh $SWEAGLE_MDS $SWEAGLE_EXPORTER args=$SWEAGLE_EXPORTER_ARGS format=$SWEAGLE_EXPORTER_FORMAT output=$SWEAGLE_EXPORTER_OUTPUT
  script:
    - echo deploy TEST environment
    - echo run tests
  when: on_success
  # possible values always, on_success, on_failure, manual

#staging:
#  stage: staging
#  only:
#    - release
#  before_script: [Use Sweagle again]
#  script:
#    - echo deploy to staging


#production:
#  stage: production
#  before_script: [Use Sweagle again]
#  script:
#    - echo deploy to production
#  when: manual
