stages:
  - build
  - uploadConfiguration
  - qualif
  - preprod
  - production

variables:

#build:
#  stage: build
#  before_script: []
#  script:
#    - echo build
#  after_script: []


uploadConfiguration:
  stage: uploadConfiguration
  only:
  - master
  script:
    - chmod +x ./sweagle_scripts/*.sh
    - echo send configuration to Sweagle
    - ./sweagle_scripts/uploadFileToSweagle.sh
    - echo configuration sent
  when: manual
  # possible values always, on_success, on_failure, manual

deployTest:
  stage: qualif
  only:
  - master
  variables:
    MDS: WEBPORTAL_CSS
    VALIDATOR: ColorValidator
  before_script:
    - echo check configuration from Sweagle
    - chmod +x ./sweagle_scripts/*.sh
    - ./sweagle_scripts/SweagleCheckConfigByMds.sh $MDS
    - ./sweagle_scripts/SweagleCheckConfigByMdsValidator.sh $MDS $VALIDATOR
  script:
    - echo deploy TEST environment
    - echo run tests
  when: manual
  # possible values always, on_success, on_failure, manual

#staging:
#  stage: staging
#  only:
#    - release
#  before_script: [Use Sweagle again]
#  script:
#    - echo deploy to staging


#production:
#  stage: production
#  before_script: [Use Sweagle again]
#  script:
#    - echo deploy to production
#  when: manual
