stages:
  - build
  - uploadConfiguration
  - qualif
  - preprod
  - production

variables:

#build:
#  stage: build
#  before_script: []
#  script:
#    - echo build
#  after_script: []

uploadOpenShiftConfiguration:
  stage: uploadConfiguration
  only:
  - master
  script:
    - echo send OpenShift configuration to Sweagle
    - chmod +x ./scripts/*.sh
    - ./scripts/SweagleUpload.sh
    - echo configuration sent
  when: manual
  # possible values always, on_success, on_failure, manual

qualif:
  stage: qualif
  only:
  - master
  variables:
    APPLI: PAYMENTS
    ENVRT: QUALIF
  before_script:
    - echo get configuration from Sweagle
    - chmod +x ./scripts/*.sh
    - ./scripts/SweagleGetConfig.sh $APPLI $ENVRT
  script:
    - echo deploy Qualif environment
    - echo run tests
  when: manual
  # possible values always, on_success, on_failure, manual

#staging:
#  stage: staging
#  only:
#    - release
#  before_script: []
#  script:
#    - echo deploy to staging


#production:
#  stage: production
#  before_script: []
#  script:
#    - echo deploy to production
#  when: manual
